openapi: 3.0.0
info:
  title: Vedtak API
  version: 1.0.0
  description: API for å hente alle vedtak knyttet til en person.
  contact:
    name: '#team-dagpenger'
servers:
  - url: https://dp-vedtak.intern.dev.nav.no
    description: dev
  - url: https://dp-vedtak.intern.nav.no
    description: prod
paths:
  /vedtak:
    post:
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vedtak'
          description: OK
      summary: Hent alle vedtak for en gitt person
      description: Hent alle vedtak for en gitt person
      security:
        - azureAd: [ ]
      requestBody:
        required: true
        content:
          application/json:
            example:
              ident: "12312312311"
            schema:
              type: object
              properties:
                ident:
                  type: string
components:
  schemas:
    Vedtak:
      type: object
      properties:
        vedtakId:
          type: string
          format: uuid
        vedtakType:
          type: string
          enum:
            - Ramme
            - Utbetaling
            - Avslag
            - Stans