/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param behandlingId
 * @param forrigeBehandlingId
 * @param eksternId
 * @param behandlingType
 * @param behandlingÅrsak
 * @param vilkårsvurderinger
 * @param aktivitetspliktInntrefferDato
 * @param kravMottatt
 * @param getårsakRevurdering
 */
data class BehandlingsdetaljerDto(

    val behandlingId: java.util.UUID,
    val forrigeBehandlingId: java.util.UUID? = null,
    val eksternId: Long,
    val behandlingType: BehandlingType,
    val behandlingÅrsak: Behandlingårsak,
    val vilkårsvurderinger: List<VilkårsvurderingDto>,
    val aktivitetspliktInntrefferDato: java.time.LocalDate? = null,
    val kravMottatt: java.time.LocalDate? = null,
    val getårsakRevurdering: ÅrsakRevurderingDto? = null,
) {
    /**
     *
     * Values: F_RSTEGANGSBEHANDLING,REVURDERING,KLAGE
     */
    enum class BehandlingType(val value: kotlin.String) {
        FØRSTEGANGSBEHANDLING("FØRSTEGANGSBEHANDLING"),
        REVURDERING("REVURDERING"),
        KLAGE("KLAGE"),
    }

    /**
     *
     * Values: KLAGE,NYEOPPLYSNINGER,SANKSJON1MND,S_KNAD,MIGRERING,GOMREGNING,KORRIGERINGUTENBREV,PAPIRS_KNAD,SATSENDRING
     */
    enum class Behandlingårsak(val value: kotlin.String) {
        KLAGE("KLAGE"),
        NYEOPPLYSNINGER("NYE_OPPLYSNINGER"),
        SANKSJON1MND("SANKSJON_1_MND"),
        SØKNAD("SØKNAD"),
        MIGRERING("MIGRERING"),
        GOMREGNING("G_OMREGNING"),
        KORRIGERINGUTENBREV("KORRIGERING_UTEN_BREV"),
        PAPIRSØKNAD("PAPIRSØKNAD"),
        SATSENDRING("SATSENDRING"),
    }
}
