/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param ident
 * @param navn
 * @param mottakerRolle
 * @param identType
 */
data class Brevmottaker(

    val ident: kotlin.String,
    val navn: kotlin.String,
    val mottakerRolle: MottakerRolle,
    val identType: IdentType,
) {
    /**
     *
     * Values: BRUKER,VERGE,FULLMEKTIG
     */
    enum class MottakerRolle(val value: kotlin.String) {
        BRUKER("BRUKER"),
        VERGE("VERGE"),
        FULLMEKTIG("FULLMEKTIG"),
    }

    /**
     *
     * Values: PERSONIDENT,ORGANISASJONSNUMMER
     */
    enum class IdentType(val value: kotlin.String) {
        PERSONIDENT("PERSONIDENT"),
        ORGANISASJONSNUMMER("ORGANISASJONSNUMMER"),
    }
}
