/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param resultat
 * @param vurderinger
 */
data class DelvilkårsvurderingDto(

    val resultat: Resultat,
    val vurderinger: List<VurderingDto>,
) {
    /**
     *
     * Values: OPPFYLT,AUTOMATISKOPPFYLT,IKKEOPPFYLT,IKKEAKTUELL,IKKETATTSTILLINGTIL,SKALIKKEVURDERES
     */
    enum class Resultat(val value: kotlin.String) {
        OPPFYLT("OPPFYLT"),
        AUTOMATISKOPPFYLT("AUTOMATISK_OPPFYLT"),
        IKKEOPPFYLT("IKKE_OPPFYLT"),
        IKKEAKTUELL("IKKE_AKTUELL"),
        IKKETATTSTILLINGTIL("IKKE_TATT_STILLING_TIL"),
        SKALIKKEVURDERES("SKAL_IKKE_VURDERES"),
    }
}
