/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param personIdent
 * @param eksternFagsakId
 * @param stønadType
 * @param brevtype
 * @param fil
 * @param journalf_rendeEnhet
 * @param saksbehandlerIdent
 * @param mottakere
 */
data class FrittståendeBrevDto(

    val personIdent: String,
    val eksternFagsakId: Long,
    val stønadType: StønadType,
    val brevtype: Brevtype,
    val fil: List<ByteArray>,
    val journalf_rendeEnhet: String,
    val saksbehandlerIdent: String,
    val mottakere: List<Brevmottaker>? = null,
) {
    /**
     *
     * Values: DAGPENGER
     */
    enum class StønadType(val value: String) {
        DAGPENGER("DAGPENGER"),
    }

    /**
     *
     * Values: INFORMASJONSBREV,INNHENTINGAVOPPLYSNINGER,VARSELOMAKTIVITETSPLIKT,VARSELOMSANKSJON,INNHENTINGAVKARAKTERUTSKRIFTHOVEDPERIODE,INNHENTINGAVKARAKTERUTSKRIFTUTVIDETPERIODE,BREVOMSVARTIDKLAGE,BREVOMFORLENGETSVARTID,BREVOMFORLENGETSVARTIDKLAGE,INFORMASJONSBREVTRUKKETS_KNAD,VARSELUTESTENGELSE,VEDTAKUTESTENGELSE
     */
    enum class Brevtype(val value: String) {
        INFORMASJONSBREV("INFORMASJONSBREV"),
        INNHENTINGAVOPPLYSNINGER("INNHENTING_AV_OPPLYSNINGER"),
        VARSELOMAKTIVITETSPLIKT("VARSEL_OM_AKTIVITETSPLIKT"),
        VARSELOMSANKSJON("VARSEL_OM_SANKSJON"),
        INNHENTINGAVKARAKTERUTSKRIFTHOVEDPERIODE("INNHENTING_AV_KARAKTERUTSKRIFT_HOVEDPERIODE"),
        INNHENTINGAVKARAKTERUTSKRIFTUTVIDETPERIODE("INNHENTING_AV_KARAKTERUTSKRIFT_UTVIDET_PERIODE"),
        BREVOMSVARTIDKLAGE("BREV_OM_SVARTID_KLAGE"),
        BREVOMFORLENGETSVARTID("BREV_OM_FORLENGET_SVARTID"),
        BREVOMFORLENGETSVARTIDKLAGE("BREV_OM_FORLENGET_SVARTID_KLAGE"),
        INFORMASJONSBREVTRUKKETS_KNAD("INFORMASJONSBREV_TRUKKET_SØKNAD"),
        VARSELUTESTENGELSE("VARSEL_UTESTENGELSE"),
        VEDTAKUTESTENGELSE("VEDTAK_UTESTENGELSE"),
    }
}
