/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param fagsak
 * @param behandling
 * @param søkerDto
 * @param vedtak
 * @param forrigeVedtak
 */
data class IverksettDagpengerdDto(

    val fagsak: FagsakdetaljerDto,
    val behandling: BehandlingsdetaljerDto,
    val søkerDto: SøkerDto,
    val vedtak: VedtaksdetaljerDagpengerDto,
    val forrigeVedtak: VedtaksdetaljerDagpengerDto? = null,
)
