/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param &#x60;data&#x60;
 * @param status
 * @param melding
 * @param frontendFeilmelding
 * @param stacktrace
 */
data class RessursBeriketSimuleringsresultat(

    val `data`: BeriketSimuleringsresultat? = null,
    val status: Status,
    val melding: kotlin.String,
    val frontendFeilmelding: kotlin.String? = null,
    val stacktrace: kotlin.String? = null,
) {
    /**
     *
     * Values: SUKSESS,FEILET,IKKEHENTET,IKKETILGANG,FUNKSJONELLFEIL
     */
    enum class Status(val value: kotlin.String) {
        SUKSESS("SUKSESS"),
        FEILET("FEILET"),
        IKKEHENTET("IKKE_HENTET"),
        IKKETILGANG("IKKE_TILGANG"),
        FUNKSJONELLFEIL("FUNKSJONELL_FEIL"),
    }
}
