/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param perioder
 * @param fomDatoNestePeriode
 * @param etterbetaling
 * @param feilutbetaling
 * @param fom
 * @param tomDatoNestePeriode
 * @param forfallsdatoNestePeriode
 * @param tidSimuleringHentet
 * @param tomSisteUtbetaling
 */
data class Simuleringsoppsummering(

    val perioder: kotlin.Array<Simuleringsperiode>,
    val fomDatoNestePeriode: java.time.LocalDate? = null,
    val etterbetaling: java.math.BigDecimal,
    val feilutbetaling: java.math.BigDecimal,
    val fom: java.time.LocalDate? = null,
    val tomDatoNestePeriode: java.time.LocalDate? = null,
    val forfallsdatoNestePeriode: java.time.LocalDate? = null,
    val tidSimuleringHentet: java.time.LocalDate? = null,
    val tomSisteUtbetaling: java.time.LocalDate? = null,
)
