/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param fom
 * @param tom
 * @param forfallsdato
 * @param nyttBel_p
 * @param tidligereUtbetalt
 * @param resultat
 * @param feilutbetaling
 */
data class Simuleringsperiode(

    val fom: java.time.LocalDate,
    val tom: java.time.LocalDate,
    val forfallsdato: java.time.LocalDate,
    val nyttBel_p: java.math.BigDecimal,
    val tidligereUtbetalt: java.math.BigDecimal,
    val resultat: java.math.BigDecimal,
    val feilutbetaling: java.math.BigDecimal,
)
