/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param utbetalinger
 * @param saksbehandlerId
 * @param eksternBehandlingId
 * @param stønadstype
 * @param eksternFagsakId
 * @param personIdent
 * @param behandlingId
 * @param vedtaksdato
 * @param forrigeBehandlingId
 */
data class SimuleringDto(

    val utbetalinger: kotlin.Array<UtbetalingDto>,
    val saksbehandlerId: kotlin.String,
    val eksternBehandlingId: kotlin.Long,
    val stønadstype: Stønadstype,
    val eksternFagsakId: kotlin.Long,
    val personIdent: kotlin.String,
    val behandlingId: java.util.UUID,
    val vedtaksdato: java.time.LocalDate,
    val forrigeBehandlingId: java.util.UUID? = null,
) {
    /**
     *
     * Values: DAGPENGER
     */
    enum class Stønadstype(val value: kotlin.String) {
        DAGPENGER("DAGPENGER"),
    }
}
