/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param simulertPostering
 * @param mottakerNummer
 * @param mottakerType
 */
data class SimuleringMottaker(

    val simulertPostering: kotlin.Array<SimulertPostering>,
    val mottakerNummer: kotlin.String? = null,
    val mottakerType: MottakerType,
) {
    /**
     *
     * Values: BRUKER,ARBGORG,ARBGPRIV
     */
    enum class MottakerType(val value: kotlin.String) {
        BRUKER("BRUKER"),
        ARBGORG("ARBG_ORG"),
        ARBGPRIV("ARBG_PRIV"),
    }
}
