/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param fagOmr_deKode
 * @param erFeilkonto
 * @param fom
 * @param tom
 * @param betalingType
 * @param bel_p
 * @param posteringType
 * @param forfallsdato
 * @param utenInntrekk
 */
data class SimulertPostering(

    val fagOmr_deKode: FagOmr_deKode,
    val erFeilkonto: kotlin.Boolean? = null,
    val fom: java.time.LocalDate,
    val tom: java.time.LocalDate,
    val betalingType: BetalingType,
    val bel_p: java.math.BigDecimal,
    val posteringType: PosteringType,
    val forfallsdato: java.time.LocalDate,
    val utenInntrekk: kotlin.Boolean,
) {
    /**
     *
     * Values: DAGPENGER
     */
    enum class FagOmr_deKode(val value: kotlin.String) {
        DAGPENGER("DAGPENGER"),
    }

    /**
     *
     * Values: DEBIT,KREDIT
     */
    enum class BetalingType(val value: kotlin.String) {
        DEBIT("DEBIT"),
        KREDIT("KREDIT"),
    }

    /**
     *
     * Values: YTELSE,FEILUTBETALING,FORSKUDSSKATT,JUSTERING,TREKK,MOTP
     */
    enum class PosteringType(val value: kotlin.String) {
        YTELSE("YTELSE"),
        FEILUTBETALING("FEILUTBETALING"),
        FORSKUDSSKATT("FORSKUDSSKATT"),
        JUSTERING("JUSTERING"),
        TREKK("TREKK"),
        MOTP("MOTP"),
    }
}
