/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param personIdent
 * @param barn
 * @param tilhørendeEnhet
 * @param adressebeskyttelse
 */
data class SøkerDto(

    val personIdent: String,
    val barn: List<BarnDto>,
    val tilhørendeEnhet: String,
    val adressebeskyttelse: Adressebeskyttelse? = null,
) {
    /**
     *
     * Values: STRENGTFORTROLIG,STRENGTFORTROLIGUTLAND,FORTROLIG,UGRADERT
     */
    enum class Adressebeskyttelse(val value: String) {
        STRENGTFORTROLIG("STRENGT_FORTROLIG"),
        STRENGTFORTROLIGUTLAND("STRENGT_FORTROLIG_UTLAND"),
        FORTROLIG("FORTROLIG"),
        UGRADERT("UGRADERT"),
    }
}
