/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param tilbakekrevingsvalg
 * @param tilbakekrevingMedVarsel
 */
data class TilbakekrevingDto(

    val tilbakekrevingsvalg: Tilbakekrevingsvalg,
    val tilbakekrevingMedVarsel: TilbakekrevingMedVarselDto? = null,
) {
    /**
     *
     * Values: OPPRETTTILBAKEKREVINGMEDVARSEL,OPPRETTTILBAKEKREVINGUTENVARSEL,IGNORERTILBAKEKREVING
     */
    enum class Tilbakekrevingsvalg(val value: kotlin.String) {
        OPPRETTTILBAKEKREVINGMEDVARSEL("OPPRETT_TILBAKEKREVING_MED_VARSEL"),
        OPPRETTTILBAKEKREVINGUTENVARSEL("OPPRETT_TILBAKEKREVING_UTEN_VARSEL"),
        IGNORERTILBAKEKREVING("IGNORER_TILBAKEKREVING"),
    }
}
