/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param beløp
 * @param inntekt
 * @param inntektsreduksjon
 * @param samordningsfradrag
 * @param periode
 * @param kildeBehandlingId
 */
data class UtbetalingDto(

    val beløp: Int,
    val inntekt: Int,
    val inntektsreduksjon: Int,
    val samordningsfradrag: Int,
    val periode: Datoperiode,
    val kildeBehandlingId: java.util.UUID? = null,
)
