/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param vedtakstidspunkt
 * @param resultat
 * @param opphørårsak
 * @param avslagårsak
 * @param saksbehandlerId
 * @param beslutterId
 * @param utbetalinger
 * @param vedtaksperioder
 * @param tilbakekreving
 * @param brevmottakere
 */
data class VedtaksdetaljerDagpengerDto(

    val vedtakstidspunkt: java.time.LocalDateTime,
    val resultat: Resultat,
    val opphørårsak: Opphørårsak? = null,
    val avslagårsak: Avslagårsak? = null,
    val saksbehandlerId: String,
    val beslutterId: String,
    val utbetalinger: List<UtbetalingDto>,
    val vedtaksperioder: List<VedtaksperiodeDagpengerDto>,
    val tilbakekreving: TilbakekrevingDto? = null,
    val brevmottakere: List<Brevmottaker>,
) {
    /**
     *
     * Values: INNVILGET,OPPH_RT,AVSL_TT
     */
    enum class Resultat(val value: String) {
        INNVILGET("INNVILGET"),
        OPPH_RT("OPPHØRT"),
        AVSL_TT("AVSLÅTT"),
    }

    /**
     *
     * Values: PERIODEUTL_PT
     */
    enum class Opphørårsak(val value: String) {
        PERIODEUTL_PT("PERIODE_UTLØPT"),
    }

    /**
     *
     * Values: VILK_RIKKEOPPFYLT,BARNOVER_TTE_R,ST_NADSTIDOPPBRUKT,MANGLENDEOPPLYSNINGER,MINDREINNTEKTSENDRINGER
     */
    enum class Avslagårsak(val value: String) {
        VILK_RIKKEOPPFYLT("VILKÅR_IKKE_OPPFYLT"),
        BARNOVER_TTE_R("BARN_OVER_ÅTTE_ÅR"),
        ST_NADSTIDOPPBRUKT("STØNADSTID_OPPBRUKT"),
        MANGLENDEOPPLYSNINGER("MANGLENDE_OPPLYSNINGER"),
        MINDREINNTEKTSENDRINGER("MINDRE_INNTEKTSENDRINGER"),
    }
}
