/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param vilk_rType
 * @param resultat
 * @param delvilk_rsvurderinger
 */
data class VilkårsvurderingDto(

    val vilk_rType: Vilk_rType,
    val resultat: Resultat,
    val delvilk_rsvurderinger: kotlin.Array<DelvilkårsvurderingDto>,
) {
    /**
     *
     * Values: FORUTG_ENDEMEDLEMSKAP,LOVLIGOPPHOLD,MORELLERFAR,SIVILSTAND,ALENEOMSORG,SAGTOPPELLERREDUSERT,AKTIVITET,TIDLIGEREVEDTAKSPERIODER,AKTIVITETARBEID,INNTEKT,ALDERP_BARN,DOKUMENTASJONTILSYNSUTGIFTER,RETTTILDAGPENGER,DOKUMENTASJONAVUTDANNING,ERUTDANNINGHENSIKTSMESSIG
     */
    enum class Vilk_rType(val value: String) {
        FORUTG_ENDEMEDLEMSKAP("FORUTGÅENDE_MEDLEMSKAP"),
        LOVLIGOPPHOLD("LOVLIG_OPPHOLD"),
        MORELLERFAR("MOR_ELLER_FAR"),
        SIVILSTAND("SIVILSTAND"),
        ALENEOMSORG("ALENEOMSORG"),
        SAGTOPPELLERREDUSERT("SAGT_OPP_ELLER_REDUSERT"),
        AKTIVITET("AKTIVITET"),
        TIDLIGEREVEDTAKSPERIODER("TIDLIGERE_VEDTAKSPERIODER"),
        AKTIVITETARBEID("AKTIVITET_ARBEID"),
        INNTEKT("INNTEKT"),
        ALDERP_BARN("ALDER_PÅ_BARN"),
        DOKUMENTASJONTILSYNSUTGIFTER("DOKUMENTASJON_TILSYNSUTGIFTER"),
        RETTTILDAGPENGER("RETT_TIL_DAGPENGER"),
        DOKUMENTASJONAVUTDANNING("DOKUMENTASJON_AV_UTDANNING"),
        ERUTDANNINGHENSIKTSMESSIG("ER_UTDANNING_HENSIKTSMESSIG"),
    }

    /**
     *
     * Values: OPPFYLT,AUTOMATISKOPPFYLT,IKKEOPPFYLT,IKKEAKTUELL,IKKETATTSTILLINGTIL,SKALIKKEVURDERES
     */
    enum class Resultat(val value: String) {
        OPPFYLT("OPPFYLT"),
        AUTOMATISKOPPFYLT("AUTOMATISK_OPPFYLT"),
        IKKEOPPFYLT("IKKE_OPPFYLT"),
        IKKEAKTUELL("IKKE_AKTUELL"),
        IKKETATTSTILLINGTIL("IKKE_TATT_STILLING_TIL"),
        SKALIKKEVURDERES("SKAL_IKKE_VURDERES"),
    }
}
