/**
 * Familie ef sak api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.dagpenger.vedtak.mediator.vedtak.iverksett.models

/**
 *
 * @param opplysningskilde
 * @param getÅrsak
 */
data class ÅrsakRevurderingDto(

    val opplysningskilde: Opplysningskilde,
    val getÅrsak: GetÅrsak,
) {
    /**
     *
     * Values: INNSENDTS_KNAD,MELDINGMODIA,INNSENDTMELDEKORT
     */
    enum class Opplysningskilde(val value: kotlin.String) {
        INNSENDTSØKNAD("INNSENDT_SØKNAD"),
        MELDINGMODIA("MELDING_MODIA"),
        INNSENDTMELDEKORT("INNSENDT_MELDEKORT"),
    }

    /**
     *
     * Values: ENDRINGINNTEKT,SYKDOM,ANNET,KLAGEOMGJ_RING,ANKEOMGJ_RING
     */
    enum class GetÅrsak(val value: kotlin.String) {
        ENDRINGINNTEKT("ENDRING_INNTEKT"),
        SYKDOM("SYKDOM"),
        ANNET("ANNET"),
        KLAGEOMGJ_RING("KLAGE_OMGJØRING"),
        ANKEOMGJ_RING("ANKE_OMGJØRING"),
    }
}
